StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{633D75250DCABE2D}" {
   Id "AR-Notification_GRAD_DOORLOCK_CLOSE_FIRST"
   Target_en_us "Close the door first you dumbass."
   Target_de_de "Tür zuerst schließen du Dödel."
   Status DEVELOPMENT_DONE
   Modified 1665010121
   Author "nomisum"
   LastChanged "nomisum"
  }
  CustomStringTableItem "{633D75250990FD1E}" {
   Id "AR-Notification_GRAD_DOORLOCK_GM_LOCKED"
   Target_en_us "Door locked for all players."
   Target_de_de "Tür für alle Spieler und KI verschlossen."
   Status DEVELOPMENT_DONE
   Modified 1665010071
   Author "nomisum"
   LastChanged "nomisum"
  }
  CustomStringTableItem "{633D7525060DD316}" {
   Id "AR-Notification_GRAD_DOORLOCK_GM_UNLOCKED"
   Target_en_us "Door unlocked for all."
   Target_de_de "Tür aufgeschlossen für jedermann."
   Status DEVELOPMENT_DONE
   Modified 1665008175
   Author "nomisum"
   LastChanged "nomisum"
  }
  CustomStringTableItem "{633D752503152EEA}" {
   Id "AR-Notification_GRAD_DOORLOCK_NO_KEY"
   Target_en_us "You have no key for this door."
   Target_de_de "Dir fehlt der Schlüssel zur Tür."
   Status DEVELOPMENT_DONE
   Modified 1665009743
   Author "nomisum"
   LastChanged "nomisum"
  }
  CustomStringTableItem "{633E0825147A1918}" {
   Id "AR-Notification_PLAYER_DIED"
   Target_en_us "%1"
   Comment "Notification shown on the side of the screen. Notifications can have various names added to it using %"
   MaxLength 50
   Modified 1665009751
   Author "nomisum"
   LastChanged "nomisum"
   Labels {
    0 405
   }
   SourceFile "{7134157CA6B1FA8E}Configs/Notifications/Notifications.conf"
  }
  CustomStringTableItem "{633E0825147A5741}" {
   Id "AR-Notification_PLAYER_KILLED_PLAYER"
   Target_en_us "%1"
   Comment "Notification shown on the side of the screen. Notifications can have various names added to it using %"
   MaxLength 50
   Modified 1665009751
   Author "nomisum"
   LastChanged "nomisum"
   Labels {
    0 405
   }
   SourceFile "{7134157CA6B1FA8E}Configs/Notifications/Notifications.conf"
  }
  CustomStringTableItem "{633E0825147AB381}" {
   Id "AR-Notification_PLAYER_KILLED_POSSESSED_AI"
   Target_en_us "%1"
   Comment "Notification shown on the side of the screen. Notifications can have various names added to it using %"
   MaxLength 50
   Modified 1665009751
   Author "nomisum"
   LastChanged "nomisum"
   Labels {
    0 405
   }
   SourceFile "{7134157CA6B1FA8E}Configs/Notifications/Notifications.conf"
  }
 }
}