StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{633E1447B95AF069}" {
   Id "AR-Notification_GRAD_DOORLOCK_CLOSE_FIRST"
   Target_en_us "Close the door first you dumbass."
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_DONE
   NonTranslatable 0
   MaxLength 0
   Modified 1665013134
   Author "nomisum"
   LastChanged "nomisum"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{633E1447B95AFF54}" {
   Id "AR-Notification_GRAD_DOORLOCK_GM_LOCKED"
   Target_en_us "Door locked for all players."
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_DONE
   NonTranslatable 0
   MaxLength 0
   Modified 1665013134
   Author "nomisum"
   LastChanged "nomisum"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{633E1447B95AFF94}" {
   Id "AR-Notification_GRAD_DOORLOCK_GM_UNLOCKED"
   Target_en_us "Door unlocked for all."
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_DONE
   NonTranslatable 0
   MaxLength 0
   Modified 1665013134
   Author "nomisum"
   LastChanged "nomisum"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{633E1447B95AFFDD}" {
   Id "AR-Notification_GRAD_DOORLOCK_NO_KEY"
   Target_en_us "You have no key for this door."
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_DONE
   NonTranslatable 0
   MaxLength 0
   Modified 1665013134
   Author "nomisum"
   LastChanged "nomisum"
   ImageLink ""
   Hidden 0
  }
 }
}